use_frameworks!

platform :ios, '10.0'

target 'XYHNetWorking_Example' do
  pod 'XYHNetWorking', :path => '../'

  target 'XYHNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
